stages:
  - diff
  - lint
  - test
diff:
  stage: diff
  image:
    name: $CI_REGISTRY_GO/golang:1.15
    entrypoint: [""]
  tags:
    - go
  script:
    - go run generate/go-generate.go $(pwd)
    - test -z "$(git diff 2> /dev/null)" || echo 'Files are not generated, issue `go run generate/go-generate.go $(pwd)` and commit the result'
    - test -z "$(git ls-files --others --exclude-standard 2> /dev/null)" || exit 'Generation created untracked files, cannot proceed'
golangci_lint:
  stage: lint
  image:
    name: $CI_REGISTRY_GO/lint:latest
    entrypoint: [""]
  tags:
    - go
  script:
    - golangci-lint run --enable-all
lint-commit-msg:
  stage: lint
  image:
    name: $CI_REGISTRY_GO/check-commit:latest
    entrypoint: [""]
  tags:
    - go
  script:
    - /check
test:
  stage: test
  image:
    name: $CI_REGISTRY_GO/golang:1.15
    entrypoint: [""]
  tags:
    - go
  script:
    - go build -v .
    - go test -v ./...
